---
- name: Check existence of Excalidraw collaboration server systemd service
  ansible.builtin.stat:
    path: "{{ sysd_docker_service_path }}/{{ excalidraw_room_identifier }}.service"
  register: excalidraw_room_service_stat

- name: Uninstall Excalidraw collaboration server systemd services and files
  when: excalidraw_room_service_stat.stat.exists | bool
  block:
    - name: Ensure Excalidraw collaboration server systemd service is stopped
      ansible.builtin.service:
        name: "{{ excalidraw_room_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Excalidraw collaboration server systemd service does not exist
      ansible.builtin.file:
        path: "{{ sysd_docker_service_path }}/{{ excalidraw_room_identifier }}.service"
        state: absent

    - name: Ensure Excalidraw collaboration server container network does not exist via community.docker.docker_network
      when: sysd_docker_net_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ excalidraw_room_container_network }}"
        state: absent

    - name: Ensure Excalidraw collaboration server container network does not exist via ansible.builtin.command
      when: sysd_docker_net_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ sysd_docker_host_command }} network rm
          {{ excalidraw_room_container_network }}
      register: network_deletion_result
      changed_when: excalidraw_room_container_network in network_deletion_result.stdout

    - name: Ensure Excalidraw collaboration server path does not exist
      ansible.builtin.file:
        path: "{{ excalidraw_room_base_path }}"
        state: absent
